name: Multi-Service Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: eunseongjo
          password: ces9645!

      - name: Build and push service-a
        uses: docker/build-push-action@v4
        with:
          context: ./smileage-inferensing-serving
          push: true
          tags: eunseongjo/smileage-inferensing-serving:latest

      - name: Build and push service-b
        uses: docker/build-push-action@v4
        with:
          context: ./smileage-frontend
          push: true
          tags: eunseongjo/smileage-frontend:latest

      - name: Build and push service-c
        uses: docker/build-push-action@v4
        with:
          context: ./smileage-DB
          push: true
          tags: eunseongjo/smileage-DB:latest

      - name: Deploy with Docker Compose
        run: docker-compose up -d
